-- Consolidated DDL schema that reduces redundant base tables
-- and models reusable components for the lending platform domain.

CREATE TABLE reference_domains (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(64) NOT NULL UNIQUE,
  name          varchar(255) NOT NULL,
  description   text,
  created_at    timestamp without time zone DEFAULT now(),
  updated_at    timestamp without time zone DEFAULT now()
);

CREATE TABLE reference_values (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id        bigint NOT NULL REFERENCES reference_domains(id),
  code             varchar(64) NOT NULL,
  name             varchar(255) NOT NULL,
  description      text,
  display_order    integer DEFAULT 0,
  is_active        boolean DEFAULT true,
  metadata         jsonb DEFAULT '{}'::jsonb,
  UNIQUE(domain_id, code)
);

CREATE TABLE entities (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type_value_id  bigint NOT NULL REFERENCES reference_values(id),
  legal_name            varchar(255),
  first_name            varchar(255),
  last_name             varchar(255),
  registration_number   varchar(255),
  date_of_birth         date,
  tax_identifier        varchar(255),
  status_value_id       bigint REFERENCES reference_values(id),
  metadata              jsonb DEFAULT '{}'::jsonb,
  created_at            timestamp without time zone DEFAULT now(),
  updated_at            timestamp without time zone DEFAULT now(),
  deleted_at            timestamp without time zone
);

CREATE TABLE entity_credentials (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id          bigint NOT NULL REFERENCES entities(id),
  credential_type_id bigint NOT NULL REFERENCES reference_values(id),
  identifier         varchar(255) NOT NULL,
  secret_hash        varchar(255) NOT NULL,
  expires_at         timestamp without time zone,
  last_used_at       timestamp without time zone,
  is_primary         boolean DEFAULT false,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(entity_id, credential_type_id, identifier)
);

CREATE TABLE entity_contacts (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id          bigint NOT NULL REFERENCES entities(id),
  contact_type_id    bigint NOT NULL REFERENCES reference_values(id),
  contact_value      varchar(255) NOT NULL,
  is_primary         boolean DEFAULT false,
  is_verified        boolean DEFAULT false,
  verified_at        timestamp without time zone,
  metadata           jsonb DEFAULT '{}'::jsonb,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now()
);

CREATE TABLE postal_addresses (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line1         varchar(255) NOT NULL,
  line2         varchar(255),
  city          varchar(255),
  district      varchar(255),
  state_region  varchar(255),
  postcode      varchar(32),
  country_code  varchar(2) NOT NULL,
  latitude      numeric(10,7),
  longitude     numeric(10,7),
  metadata      jsonb DEFAULT '{}'::jsonb,
  created_at    timestamp without time zone DEFAULT now(),
  updated_at    timestamp without time zone DEFAULT now()
);

CREATE TABLE entity_addresses (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id          bigint NOT NULL REFERENCES entities(id),
  address_id         bigint NOT NULL REFERENCES postal_addresses(id),
  usage_type_id      bigint NOT NULL REFERENCES reference_values(id),
  is_primary         boolean DEFAULT false,
  valid_from         date,
  valid_to           date,
  metadata           jsonb DEFAULT '{}'::jsonb,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(entity_id, usage_type_id, address_id)
);

CREATE TABLE financial_accounts (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id          bigint NOT NULL REFERENCES entities(id),
  account_type_id    bigint NOT NULL REFERENCES reference_values(id),
  account_reference  varchar(255) NOT NULL,
  bank_name          varchar(255),
  iban               varchar(34),
  bic                varchar(11),
  sort_code          varchar(16),
  currency_code      varchar(3),
  metadata           jsonb DEFAULT '{}'::jsonb,
  valid_from         date,
  valid_to           date,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(entity_id, account_reference)
);

CREATE TABLE attribute_definitions (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id          bigint NOT NULL REFERENCES reference_domains(id),
  code               varchar(128) NOT NULL,
  name               varchar(255) NOT NULL,
  data_type          varchar(32) NOT NULL,
  default_value      text,
  is_required        boolean DEFAULT false,
  metadata           jsonb DEFAULT '{}'::jsonb,
  UNIQUE(domain_id, code)
);

CREATE TABLE attribute_assignments (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id     bigint NOT NULL REFERENCES attribute_definitions(id),
  owner_type        varchar(64) NOT NULL,
  owner_id          bigint NOT NULL,
  value_text        text,
  value_number      numeric(22,8),
  value_date        date,
  value_json        jsonb,
  valid_from        timestamp without time zone,
  valid_to          timestamp without time zone,
  created_at        timestamp without time zone DEFAULT now(),
  updated_at        timestamp without time zone DEFAULT now(),
  UNIQUE(definition_id, owner_type, owner_id, COALESCE(valid_from, '1970-01-01'))
);

CREATE TABLE assets (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_type_value_id   bigint NOT NULL REFERENCES reference_values(id),
  asset_identifier      varchar(255),
  description           text,
  status_value_id       bigint REFERENCES reference_values(id),
  owning_entity_id      bigint REFERENCES entities(id),
  primary_address_id    bigint REFERENCES postal_addresses(id),
  acquisition_date      date,
  disposal_date         date,
  metadata              jsonb DEFAULT '{}'::jsonb,
  created_at            timestamp without time zone DEFAULT now(),
  updated_at            timestamp without time zone DEFAULT now()
);

CREATE TABLE asset_relationships (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id                bigint NOT NULL REFERENCES assets(id),
  entity_id               bigint NOT NULL REFERENCES entities(id),
  relationship_type_id    bigint NOT NULL REFERENCES reference_values(id),
  start_date              date,
  end_date                date,
  metadata                jsonb DEFAULT '{}'::jsonb,
  UNIQUE(asset_id, entity_id, relationship_type_id)
);

CREATE TABLE asset_coverages (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id                bigint NOT NULL REFERENCES assets(id),
  provider_entity_id      bigint REFERENCES entities(id),
  coverage_type_id        bigint NOT NULL REFERENCES reference_values(id),
  policy_number           varchar(255),
  coverage_amount         numeric(22,2),
  premium_amount          numeric(22,2),
  start_date              date,
  end_date                date,
  metadata                jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE asset_metrics (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id            bigint NOT NULL REFERENCES assets(id),
  metric_type_id      bigint NOT NULL REFERENCES reference_values(id),
  metric_value_number numeric(22,6),
  metric_value_text   text,
  metric_value_date   date,
  source_reference    varchar(255),
  effective_date      date NOT NULL,
  metadata            jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE deals (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_number             varchar(64) NOT NULL UNIQUE,
  deal_type_value_id      bigint NOT NULL REFERENCES reference_values(id),
  status_value_id         bigint NOT NULL REFERENCES reference_values(id),
  primary_entity_id       bigint REFERENCES entities(id),
  originating_entity_id   bigint REFERENCES entities(id),
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  closed_at               timestamp without time zone,
  metadata                jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE deal_versions (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id             bigint NOT NULL REFERENCES deals(id),
  version_number      integer NOT NULL,
  effective_date      date NOT NULL,
  status_value_id     bigint REFERENCES reference_values(id),
  description         text,
  created_by_entity_id bigint REFERENCES entities(id),
  created_at          timestamp without time zone DEFAULT now(),
  UNIQUE(deal_id, version_number)
);

CREATE TABLE deal_participants (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                   bigint NOT NULL REFERENCES deals(id),
  entity_id                 bigint NOT NULL REFERENCES entities(id),
  participant_role_id       bigint NOT NULL REFERENCES reference_values(id),
  start_date                date,
  end_date                  date,
  metadata                  jsonb DEFAULT '{}'::jsonb,
  UNIQUE(deal_id, entity_id, participant_role_id)
);

CREATE TABLE deal_assets (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                 bigint NOT NULL REFERENCES deals(id),
  asset_id                bigint NOT NULL REFERENCES assets(id),
  relationship_type_id    bigint NOT NULL REFERENCES reference_values(id),
  exposure_amount         numeric(22,2),
  ltv_ratio               numeric(9,4),
  metadata                jsonb DEFAULT '{}'::jsonb,
  UNIQUE(deal_id, asset_id, relationship_type_id)
);

CREATE TABLE entity_relationships (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_entity_id          bigint NOT NULL REFERENCES entities(id),
  to_entity_id            bigint NOT NULL REFERENCES entities(id),
  relationship_type_id    bigint NOT NULL REFERENCES reference_values(id),
  related_role_id         bigint REFERENCES reference_values(id),
  deal_id                 bigint REFERENCES deals(id),
  asset_id                bigint REFERENCES assets(id),
  started_at              timestamp without time zone,
  ended_at                timestamp without time zone,
  metadata                jsonb DEFAULT '{}'::jsonb,
  UNIQUE(from_entity_id, to_entity_id, relationship_type_id, COALESCE(deal_id, 0), COALESCE(asset_id, 0))
);

CREATE TABLE deal_terms (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id              bigint NOT NULL REFERENCES deals(id),
  version_id           bigint REFERENCES deal_versions(id),
  term_type_id         bigint NOT NULL REFERENCES reference_values(id),
  amount               numeric(22,2),
  percentage           numeric(9,4),
  rate                 numeric(9,4),
  term_json            jsonb,
  effective_date       date NOT NULL,
  expiry_date          date,
  created_at           timestamp without time zone DEFAULT now()
);

CREATE TABLE deal_settings (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                bigint NOT NULL REFERENCES deals(id),
  setting_type_id        bigint NOT NULL REFERENCES reference_values(id),
  value_json             jsonb NOT NULL,
  inherited_from_id      bigint REFERENCES deal_settings(id),
  created_at             timestamp without time zone DEFAULT now(),
  updated_at             timestamp without time zone DEFAULT now(),
  UNIQUE(deal_id, setting_type_id)
);

CREATE TABLE workflow_definitions (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type               varchar(64) NOT NULL,
  scope_identifier         varchar(128),
  name                     varchar(255) NOT NULL,
  trigger_event_type_id    bigint REFERENCES reference_values(id),
  description              text,
  created_by_entity_id     bigint REFERENCES entities(id),
  created_at               timestamp without time zone DEFAULT now(),
  updated_at               timestamp without time zone DEFAULT now()
);

CREATE TABLE workflow_steps (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id           bigint NOT NULL REFERENCES workflow_definitions(id),
  step_number             integer NOT NULL,
  name                    varchar(255) NOT NULL,
  step_type_id            bigint NOT NULL REFERENCES reference_values(id),
  assignee_role_id        bigint REFERENCES reference_values(id),
  due_in_days             integer,
  metadata                jsonb DEFAULT '{}'::jsonb,
  UNIQUE(definition_id, step_number)
);

CREATE TABLE workflow_instances (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id        bigint NOT NULL REFERENCES workflow_definitions(id),
  deal_id              bigint REFERENCES deals(id),
  asset_id             bigint REFERENCES assets(id),
  entity_id            bigint REFERENCES entities(id),
  status_value_id      bigint NOT NULL REFERENCES reference_values(id),
  started_at           timestamp without time zone DEFAULT now(),
  completed_at         timestamp without time zone
);

CREATE TABLE workflow_events (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id             bigint NOT NULL REFERENCES workflow_instances(id),
  step_id                 bigint REFERENCES workflow_steps(id),
  event_type_id           bigint NOT NULL REFERENCES reference_values(id),
  performed_by_entity_id  bigint REFERENCES entities(id),
  event_at                timestamp without time zone DEFAULT now(),
  notes                   text,
  metadata                jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE documents (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_id         bigint NOT NULL REFERENCES reference_values(id),
  title                    varchar(255) NOT NULL,
  description              text,
  originating_entity_id    bigint REFERENCES entities(id),
  uploaded_by_entity_id    bigint REFERENCES entities(id),
  uploaded_at              timestamp without time zone DEFAULT now(),
  file_id                  bigint NOT NULL,
  metadata                 jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE files (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_key     varchar(512) NOT NULL UNIQUE,
  file_name       varchar(255) NOT NULL,
  mime_type       varchar(255) NOT NULL,
  byte_size       bigint NOT NULL,
  checksum        varchar(128),
  created_at      timestamp without time zone DEFAULT now(),
  created_by_entity_id bigint REFERENCES entities(id)
);

ALTER TABLE documents
  ADD CONSTRAINT documents_file_fk FOREIGN KEY (file_id) REFERENCES files(id);

CREATE TABLE document_links (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id        bigint NOT NULL REFERENCES documents(id),
  linked_type        varchar(64) NOT NULL,
  linked_id          bigint NOT NULL,
  link_role_id       bigint REFERENCES reference_values(id),
  is_primary         boolean DEFAULT false,
  created_at         timestamp without time zone DEFAULT now(),
  UNIQUE(document_id, linked_type, linked_id, COALESCE(link_role_id, 0))
);

CREATE TABLE notes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_entity_id      bigint REFERENCES entities(id),
  note_body             text NOT NULL,
  visibility_value_id   bigint REFERENCES reference_values(id),
  created_at            timestamp without time zone DEFAULT now(),
  updated_at            timestamp without time zone DEFAULT now()
);

CREATE TABLE note_links (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id            bigint NOT NULL REFERENCES notes(id),
  linked_type        varchar(64) NOT NULL,
  linked_id          bigint NOT NULL,
  link_role_id       bigint REFERENCES reference_values(id),
  UNIQUE(note_id, linked_type, linked_id)
);

CREATE TABLE notification_templates (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_type_id      bigint NOT NULL REFERENCES reference_values(id),
  name                 varchar(255) NOT NULL,
  subject              varchar(255),
  body                 text NOT NULL,
  default_sender       varchar(255),
  metadata             jsonb DEFAULT '{}'::jsonb,
  created_at           timestamp without time zone DEFAULT now(),
  updated_at           timestamp without time zone DEFAULT now()
);

CREATE TABLE notifications (
  id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id                bigint REFERENCES notification_templates(id),
  triggering_event_type_id   bigint REFERENCES reference_values(id),
  payload_json               jsonb,
  sent_by_entity_id          bigint REFERENCES entities(id),
  status_value_id            bigint REFERENCES reference_values(id),
  scheduled_at               timestamp without time zone,
  sent_at                    timestamp without time zone,
  created_at                 timestamp without time zone DEFAULT now()
);

CREATE TABLE notification_targets (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id         bigint NOT NULL REFERENCES notifications(id),
  target_entity_id        bigint REFERENCES entities(id),
  target_address          varchar(255),
  channel_type_id         bigint NOT NULL REFERENCES reference_values(id),
  delivery_status_id      bigint REFERENCES reference_values(id),
  delivery_reference      varchar(255),
  sent_at                 timestamp without time zone,
  response_payload        jsonb
);

CREATE TABLE financial_transactions (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                     bigint REFERENCES deals(id),
  entity_id                   bigint REFERENCES entities(id),
  transaction_type_id         bigint NOT NULL REFERENCES reference_values(id),
  gross_amount                numeric(22,2) NOT NULL,
  net_amount                  numeric(22,2),
  currency_code               varchar(3) NOT NULL,
  transaction_date            date NOT NULL,
  status_value_id             bigint REFERENCES reference_values(id),
  external_reference          varchar(255),
  metadata                    jsonb DEFAULT '{}'::jsonb,
  created_at                  timestamp without time zone DEFAULT now()
);

CREATE TABLE financial_allocations (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id              bigint NOT NULL REFERENCES financial_transactions(id),
  allocation_type_id          bigint NOT NULL REFERENCES reference_values(id),
  amount                      numeric(22,2) NOT NULL,
  reference_type              varchar(64),
  reference_id                bigint,
  metadata                    jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE transaction_attempts (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id              bigint NOT NULL REFERENCES financial_transactions(id),
  attempt_number              integer NOT NULL,
  attempted_at                timestamp without time zone DEFAULT now(),
  channel_type_id             bigint REFERENCES reference_values(id),
  status_value_id             bigint REFERENCES reference_values(id),
  response_payload            jsonb,
  error_message               text,
  UNIQUE(transaction_id, attempt_number)
);

CREATE TABLE pricing_schedules (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                     bigint NOT NULL REFERENCES deals(id),
  schedule_type_id            bigint NOT NULL REFERENCES reference_values(id),
  base_rate                   numeric(9,4),
  margin_rate                 numeric(9,4),
  floor_rate                  numeric(9,4),
  ceiling_rate                numeric(9,4),
  effective_date              date NOT NULL,
  expiry_date                 date,
  source_reference            varchar(255),
  metadata                    jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE pricing_history (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id                 bigint NOT NULL REFERENCES pricing_schedules(id),
  change_type_id              bigint REFERENCES reference_values(id),
  old_value_json              jsonb,
  new_value_json              jsonb,
  changed_at                  timestamp without time zone DEFAULT now(),
  changed_by_entity_id        bigint REFERENCES entities(id)
);

CREATE TABLE drawdowns (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                 bigint NOT NULL REFERENCES deals(id),
  requested_amount        numeric(22,2) NOT NULL,
  approved_amount         numeric(22,2),
  currency_code           varchar(3) NOT NULL,
  status_value_id         bigint REFERENCES reference_values(id),
  requested_at            timestamp without time zone DEFAULT now(),
  approved_at             timestamp without time zone,
  metadata                jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE drawdown_events (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drawdown_id             bigint NOT NULL REFERENCES drawdowns(id),
  event_type_id           bigint NOT NULL REFERENCES reference_values(id),
  status_value_id         bigint REFERENCES reference_values(id),
  occurred_at             timestamp without time zone NOT NULL,
  recorded_by_entity_id   bigint REFERENCES entities(id),
  payload_json            jsonb
);

CREATE TABLE drawdown_checks (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drawdown_id             bigint NOT NULL REFERENCES drawdowns(id),
  check_type_id           bigint NOT NULL REFERENCES reference_values(id),
  is_passed               boolean,
  checked_at              timestamp without time zone,
  checked_by_entity_id    bigint REFERENCES entities(id),
  notes                   text
);

CREATE TABLE quotes (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  originating_entity_id       bigint REFERENCES entities(id),
  deal_id                     bigint REFERENCES deals(id),
  quote_status_id             bigint REFERENCES reference_values(id),
  valid_from                  date NOT NULL,
  valid_to                    date,
  total_amount                numeric(22,2),
  currency_code               varchar(3) NOT NULL,
  metadata                    jsonb DEFAULT '{}'::jsonb,
  created_at                  timestamp without time zone DEFAULT now()
);

CREATE TABLE quote_recipients (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id                    bigint NOT NULL REFERENCES quotes(id),
  recipient_entity_id         bigint REFERENCES entities(id),
  recipient_contact           varchar(255),
  channel_type_id             bigint REFERENCES reference_values(id),
  sent_at                     timestamp without time zone,
  acknowledgement_status_id   bigint REFERENCES reference_values(id)
);

CREATE TABLE sales_orders (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id                    bigint REFERENCES quotes(id),
  deal_id                     bigint REFERENCES deals(id),
  order_status_id             bigint REFERENCES reference_values(id),
  placed_at                   timestamp without time zone DEFAULT now(),
  fulfilled_at                timestamp without time zone,
  metadata                    jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE forms (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_code               varchar(128) NOT NULL,
  name                    varchar(255) NOT NULL,
  version                 integer NOT NULL,
  status_value_id         bigint REFERENCES reference_values(id),
  schema_json             jsonb NOT NULL,
  created_by_entity_id    bigint REFERENCES entities(id),
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  UNIQUE(form_code, version)
);

CREATE TABLE form_responses (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id                 bigint NOT NULL REFERENCES forms(id),
  respondent_entity_id    bigint REFERENCES entities(id),
  deal_id                 bigint REFERENCES deals(id),
  asset_id                bigint REFERENCES assets(id),
  status_value_id         bigint REFERENCES reference_values(id),
  submitted_at            timestamp without time zone,
  response_json           jsonb,
  metadata                jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE form_documents (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_response_id        bigint NOT NULL REFERENCES form_responses(id),
  document_id             bigint NOT NULL REFERENCES documents(id),
  UNIQUE(form_response_id, document_id)
);

CREATE TABLE valuations (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id                bigint NOT NULL REFERENCES assets(id),
  valuation_type_id       bigint REFERENCES reference_values(id),
  valuation_amount        numeric(22,2) NOT NULL,
  valuation_date          date NOT NULL,
  source_reference        varchar(255),
  metadata                jsonb DEFAULT '{}'::jsonb,
  created_at              timestamp without time zone DEFAULT now()
);

CREATE TABLE system_jobs (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_key                 varchar(255) NOT NULL,
  payload_json            jsonb NOT NULL,
  status_value_id         bigint REFERENCES reference_values(id),
  available_at            timestamp without time zone,
  attempts                integer DEFAULT 0,
  last_error              text,
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now()
);

CREATE TABLE audit_events (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_entity_id         bigint REFERENCES entities(id),
  scope_type              varchar(64) NOT NULL,
  scope_id                bigint,
  event_type_id           bigint REFERENCES reference_values(id),
  event_at                timestamp without time zone DEFAULT now(),
  changes_json            jsonb,
  ip_address              varchar(64),
  user_agent              varchar(255)
);

CREATE TABLE integration_settings (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_type_id     bigint NOT NULL REFERENCES reference_values(id),
  configuration_json      jsonb NOT NULL,
  is_active               boolean DEFAULT true,
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  UNIQUE(integration_type_id)
);

CREATE TABLE system_settings (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key             varchar(255) NOT NULL,
  scope_type              varchar(64),
  scope_id                bigint,
  value_json              jsonb NOT NULL,
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  UNIQUE(setting_key, COALESCE(scope_type, ''), COALESCE(scope_id, 0))
);
