
CREATE OR REPLACE TABLE activity_logs (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_name       varchar(255),
  description    text NOT NULL,
  subject_type   varchar(128),
  subject_id     bigint,
  event          varchar(255),
  causer_type    varchar(128),
  causer_id      bigint,
  batch_uuid     char(36),
  created_at     timestamp without time zone DEFAULT now(),
  updated_at     timestamp without time zone DEFAULT now(),
  deleted_at     timestamp without time zone
);

CREATE OR REPLACE INDEX activity_logs_subject_idx ON activity_logs (subject_type, subject_id);
CREATE OR REPLACE INDEX activity_logs_causer_idx ON activity_logs (causer_type, causer_id);
CREATE OR REPLACE INDEX activity_logs_log_name_idx ON activity_logs (log_name);

CREATE OR REPLACE TABLE reference_domains (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          varchar(64) NOT NULL UNIQUE,
  name          varchar(255) NOT NULL,
  description   text,
  created_at    timestamp without time zone DEFAULT now(),
  updated_at    timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE reference_values (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id        bigint NOT NULL REFERENCES reference_domains(id),
  code             varchar(64) NOT NULL,
  name             varchar(255) NOT NULL,
  description      text,
  display_order    integer DEFAULT 0,
  is_active        boolean DEFAULT true,
  UNIQUE(domain_id, code)
);

CREATE OR REPLACE TABLE entities (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type_value_id  bigint NOT NULL REFERENCES reference_values(id),
  legal_name            varchar(255),
  first_name            varchar(255),
  middle_name           varchar(255),
  last_name             varchar(255),
  preferred_name        varchar(255),
  title                 varchar(255),
  salutation            varchar(255),
  gender_value_id       bigint REFERENCES reference_values(id),
  registration_number   varchar(255),
  date_of_birth         date,
  tax_identifier        varchar(255),
  email_address         varchar(255),
  secondary_email       varchar(255),
  phone_number          varchar(64),
  mobile_number         varchar(64),
  status_value_id       bigint REFERENCES reference_values(id),
  created_at            timestamp without time zone DEFAULT now(),
  updated_at            timestamp without time zone DEFAULT now(),
  deleted_at            timestamp without time zone
);

CREATE OR REPLACE TABLE entity_credentials (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id          bigint NOT NULL REFERENCES entities(id),
  credential_type_id bigint NOT NULL REFERENCES reference_values(id),
  identifier         varchar(255) NOT NULL,
  secret_hash        varchar(255) NOT NULL,
  expires_at         timestamp without time zone,
  last_used_at       timestamp without time zone,
  is_primary         boolean DEFAULT false,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(entity_id, credential_type_id, identifier)
);

CREATE OR REPLACE TABLE contact_points (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contactable_type   varchar(128) NOT NULL,
  contactable_id     bigint NOT NULL,
  contact_type_id    bigint NOT NULL REFERENCES reference_values(id),
  contact_value      varchar(255) NOT NULL,
  label              varchar(255),
  is_primary         boolean DEFAULT false,
  is_verified        boolean DEFAULT false,
  verified_at        timestamp without time zone,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(contactable_type, contactable_id, contact_type_id, contact_value)
);

CREATE OR REPLACE INDEX contact_points_contactable_idx ON contact_points (contactable_type, contactable_id);

CREATE OR REPLACE TABLE postal_addresses (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line1          varchar(255) NOT NULL,
  line2          varchar(255),
  line3          varchar(255),
  street         varchar(255),
  house_number   varchar(64),
  city           varchar(255),
  district       varchar(255),
  county         varchar(255),
  state_region   varchar(255),
  postcode       varchar(32),
  country_code   varchar(2) NOT NULL,
  latitude       numeric(10,7),
  longitude      numeric(10,7),
  created_at     timestamp without time zone DEFAULT now(),
  updated_at     timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE address_links (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addressable_type   varchar(128) NOT NULL,
  addressable_id     bigint NOT NULL,
  address_id         bigint NOT NULL REFERENCES postal_addresses(id),
  usage_type_id      bigint NOT NULL REFERENCES reference_values(id),
  is_primary         boolean DEFAULT false,
  valid_from         date,
  valid_to           date,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(addressable_type, addressable_id, usage_type_id, address_id)
);

CREATE OR REPLACE INDEX address_links_addressable_idx ON address_links (addressable_type, addressable_id);

CREATE OR REPLACE TABLE financial_accounts (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accountable_type   varchar(128) NOT NULL,
  accountable_id     bigint NOT NULL,
  account_type_id    bigint NOT NULL REFERENCES reference_values(id),
  account_reference  varchar(255) NOT NULL,
  bank_name          varchar(255),
  iban               varchar(34),
  bic                varchar(11),
  sort_code          varchar(16),
  currency_code      varchar(3),
  valid_from         date,
  valid_to           date,
  created_at         timestamp without time zone DEFAULT now(),
  updated_at         timestamp without time zone DEFAULT now(),
  UNIQUE(accountable_type, accountable_id, account_reference)
);

CREATE OR REPLACE INDEX financial_accounts_accountable_idx ON financial_accounts (accountable_type, accountable_id);

CREATE OR REPLACE TABLE attribute_definitions (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id          bigint NOT NULL REFERENCES reference_domains(id),
  code               varchar(128) NOT NULL,
  name               varchar(255) NOT NULL,
  data_type          varchar(32) NOT NULL,
  default_value      text,
  is_required        boolean DEFAULT false,
  UNIQUE(domain_id, code)
);

CREATE OR REPLACE TABLE attribute_assignments (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id     bigint NOT NULL REFERENCES attribute_definitions(id),
  owner_type        varchar(64) NOT NULL,
  owner_id          bigint NOT NULL,
  value_text        text,
  value_number      numeric(22,8),
  value_date        date,
  value_boolean     boolean,
  valid_from        timestamp without time zone,
  valid_to          timestamp without time zone,
  created_at        timestamp without time zone DEFAULT now(),
  updated_at        timestamp without time zone DEFAULT now(),
  UNIQUE(definition_id, owner_type, owner_id, COALESCE(valid_from, '1970-01-01'))
);

CREATE OR REPLACE TABLE assets (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_type_value_id   bigint NOT NULL REFERENCES reference_values(id),
  asset_identifier      varchar(255),
  description           text,
  status_value_id       bigint REFERENCES reference_values(id),
  owning_entity_id      bigint REFERENCES entities(id),
  primary_address_id    bigint REFERENCES postal_addresses(id),
  acquisition_date      date,
  disposal_date         date,
  created_at            timestamp without time zone DEFAULT now(),
  updated_at            timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE relationship_links (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  left_type               varchar(128) NOT NULL,
  left_id                 bigint NOT NULL,
  right_type              varchar(128) NOT NULL,
  right_id                bigint NOT NULL,
  relationship_type_id    bigint NOT NULL REFERENCES reference_values(id),
  role_value_id           bigint REFERENCES reference_values(id),
  context_type            varchar(128),
  context_id              bigint,
  status_value_id         bigint REFERENCES reference_values(id),
  amount_value            numeric(22,2),
  ratio_value             numeric(9,4),
  start_date              date,
  end_date                date
  started_at              timestamp without time zone,
  ended_at                timestamp without time zone,
  UNIQUE(left_type, left_id, right_type, right_id, relationship_type_id, COALESCE(context_type, ''), COALESCE(context_id, 0))
);

CREATE OR REPLACE INDEX relationship_links_left_idx ON relationship_links (left_type, left_id);
CREATE OR REPLACE INDEX relationship_links_right_idx ON relationship_links (right_type, right_id);

CREATE OR REPLACE TABLE asset_coverages (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id                bigint NOT NULL REFERENCES assets(id),
  provider_entity_id      bigint REFERENCES entities(id),
  coverage_type_id        bigint NOT NULL REFERENCES reference_values(id),
  policy_number           varchar(255),
  coverage_amount         numeric(22,2),
  premium_amount          numeric(22,2),
  start_date              date,
  end_date                date
);

CREATE OR REPLACE TABLE asset_metrics (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id            bigint NOT NULL REFERENCES assets(id),
  metric_type_id      bigint NOT NULL REFERENCES reference_values(id),
  metric_value_number numeric(22,6),
  metric_value_text   text,
  metric_value_date   date,
  source_reference    varchar(255),
  effective_date      date NOT NULL
);

CREATE OR REPLACE TABLE deals (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_number             varchar(64) NOT NULL UNIQUE,
  deal_type_value_id      bigint NOT NULL REFERENCES reference_values(id),
  status_value_id         bigint NOT NULL REFERENCES reference_values(id),
  primary_entity_id       bigint REFERENCES entities(id),
  originating_entity_id   bigint REFERENCES entities(id),
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  closed_at               timestamp without time zone
);

CREATE OR REPLACE TABLE deal_versions (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id             bigint NOT NULL REFERENCES deals(id),
  version_number      integer NOT NULL,
  effective_date      date NOT NULL,
  status_value_id     bigint REFERENCES reference_values(id),
  description         text,
  created_by_entity_id bigint REFERENCES entities(id),
  created_at          timestamp without time zone DEFAULT now(),
  UNIQUE(deal_id, version_number)
);

CREATE OR REPLACE TABLE deal_terms (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id              bigint NOT NULL REFERENCES deals(id),
  version_id           bigint REFERENCES deal_versions(id),
  term_type_id         bigint NOT NULL REFERENCES reference_values(id),
  amount               numeric(22,2),
  percentage           numeric(9,4),
  rate                 numeric(9,4),
  term_value_text      text,
  term_value_number    numeric(22,6),
  term_value_date      date,
  effective_date       date NOT NULL,
  expiry_date          date,
  created_at           timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE deal_settings (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                bigint NOT NULL REFERENCES deals(id),
  setting_type_id        bigint NOT NULL REFERENCES reference_values(id),
  value_text             text,
  value_number           numeric(22,6),
  value_boolean          boolean,
  value_date             date,
  inherited_from_id      bigint REFERENCES deal_settings(id),
  created_at             timestamp without time zone DEFAULT now(),
  updated_at             timestamp without time zone DEFAULT now(),
  UNIQUE(deal_id, setting_type_id)
);

CREATE OR REPLACE TABLE workflow_definitions (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type               varchar(64) NOT NULL,
  scope_identifier         varchar(128),
  name                     varchar(255) NOT NULL,
  trigger_event_type_id    bigint REFERENCES reference_values(id),
  description              text,
  created_by_entity_id     bigint REFERENCES entities(id),
  created_at               timestamp without time zone DEFAULT now(),
  updated_at               timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE workflow_steps (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id           bigint NOT NULL REFERENCES workflow_definitions(id),
  step_number             integer NOT NULL,
  name                    varchar(255) NOT NULL,
  step_type_id            bigint NOT NULL REFERENCES reference_values(id),
  assignee_role_id        bigint REFERENCES reference_values(id),
  due_in_days             integer,
  UNIQUE(definition_id, step_number)
);

CREATE OR REPLACE TABLE workflow_instances (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id        bigint NOT NULL REFERENCES workflow_definitions(id),
  subject_type         varchar(128),
  subject_id           bigint,
  status_value_id      bigint NOT NULL REFERENCES reference_values(id),
  started_at           timestamp without time zone DEFAULT now(),
  completed_at         timestamp without time zone
);

CREATE OR REPLACE INDEX workflow_instances_subject_idx ON workflow_instances (subject_type, subject_id);

CREATE OR REPLACE TABLE workflow_events (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id             bigint NOT NULL REFERENCES workflow_instances(id),
  step_id                 bigint REFERENCES workflow_steps(id),
  event_type_id           bigint NOT NULL REFERENCES reference_values(id),
  performed_by_entity_id  bigint REFERENCES entities(id),
  event_at                timestamp without time zone DEFAULT now(),
  notes                   text
);

CREATE OR REPLACE TABLE documents (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type_id         bigint NOT NULL REFERENCES reference_values(id),
  title                    varchar(255) NOT NULL,
  description              text,
  originating_entity_id    bigint REFERENCES entities(id),
  uploaded_by_entity_id    bigint REFERENCES entities(id),
  uploaded_at              timestamp without time zone DEFAULT now(),
  file_id                  bigint NOT NULL
);

CREATE OR REPLACE TABLE files (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_key     varchar(512) NOT NULL UNIQUE,
  file_name       varchar(255) NOT NULL,
  mime_type       varchar(255) NOT NULL,
  byte_size       bigint NOT NULL,
  checksum        varchar(128),
  created_at      timestamp without time zone DEFAULT now(),
  created_by_entity_id bigint REFERENCES entities(id)
);

ALTER TABLE documents
  ADD CONSTRAINT documents_file_fk FOREIGN KEY (file_id) REFERENCES files(id);

CREATE OR REPLACE TABLE document_links (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id        bigint NOT NULL REFERENCES documents(id),
  linkable_type      varchar(128) NOT NULL,
  linkable_id        bigint NOT NULL,
  link_role_id       bigint REFERENCES reference_values(id),
  is_primary         boolean DEFAULT false,
  created_at         timestamp without time zone DEFAULT now(),
  UNIQUE(document_id, linkable_type, linkable_id, COALESCE(link_role_id, 0))
);

CREATE OR REPLACE INDEX document_links_linkable_idx ON document_links (linkable_type, linkable_id);

CREATE OR REPLACE TABLE notes (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_entity_id      bigint REFERENCES entities(id),
  note_body             text NOT NULL,
  visibility_value_id   bigint REFERENCES reference_values(id),
  created_at            timestamp without time zone DEFAULT now(),
  updated_at            timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE note_links (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id            bigint NOT NULL REFERENCES notes(id),
  notable_type       varchar(128) NOT NULL,
  notable_id         bigint NOT NULL,
  link_role_id       bigint REFERENCES reference_values(id),
  UNIQUE(note_id, notable_type, notable_id)
);

CREATE OR REPLACE INDEX note_links_notable_idx ON note_links (notable_type, notable_id);

CREATE OR REPLACE TABLE notification_templates (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_type_id      bigint NOT NULL REFERENCES reference_values(id),
  name                 varchar(255) NOT NULL,
  subject              varchar(255),
  body                 text NOT NULL,
  default_sender       varchar(255),
  created_at           timestamp without time zone DEFAULT now(),
  updated_at           timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE notifications (
  id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id                bigint REFERENCES notification_templates(id),
  triggering_event_type_id   bigint REFERENCES reference_values(id),
  context_reference_type     varchar(128),
  context_reference_id       bigint,
  context_summary            text,
  sent_by_entity_id          bigint REFERENCES entities(id),
  status_value_id            bigint REFERENCES reference_values(id),
  scheduled_at               timestamp without time zone,
  sent_at                    timestamp without time zone,
  created_at                 timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE notification_targets (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id         bigint NOT NULL REFERENCES notifications(id),
  target_type             varchar(128),
  target_id               bigint,
  target_address          varchar(255),
  channel_type_id         bigint NOT NULL REFERENCES reference_values(id),
  delivery_status_id      bigint REFERENCES reference_values(id),
  delivery_reference      varchar(255),
  sent_at                 timestamp without time zone,
  response_code           varchar(64),
  response_message        text
);

CREATE OR REPLACE INDEX notification_targets_target_idx ON notification_targets (target_type, target_id);

CREATE OR REPLACE TABLE financial_transactions (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                     bigint REFERENCES deals(id),
  counterparty_type           varchar(128),
  counterparty_id             bigint,
  transaction_type_id         bigint NOT NULL REFERENCES reference_values(id),
  gross_amount                numeric(22,2) NOT NULL,
  net_amount                  numeric(22,2),
  currency_code               varchar(3) NOT NULL,
  transaction_date            date NOT NULL,
  status_value_id             bigint REFERENCES reference_values(id),
  external_reference          varchar(255),
  created_at                  timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE INDEX financial_transactions_counterparty_idx ON financial_transactions (counterparty_type, counterparty_id);

CREATE OR REPLACE TABLE financial_allocations (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id              bigint NOT NULL REFERENCES financial_transactions(id),
  allocation_type_id          bigint NOT NULL REFERENCES reference_values(id),
  amount                      numeric(22,2) NOT NULL,
  reference_type              varchar(64),
  reference_id                bigint
);

CREATE OR REPLACE TABLE transaction_attempts (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id              bigint NOT NULL REFERENCES financial_transactions(id),
  attempt_number              integer NOT NULL,
  attempted_at                timestamp without time zone DEFAULT now(),
  channel_type_id             bigint REFERENCES reference_values(id),
  status_value_id             bigint REFERENCES reference_values(id),
  response_code               varchar(64),
  response_message            text,
  error_message               text,
  UNIQUE(transaction_id, attempt_number)
);

CREATE OR REPLACE TABLE pricing_schedules (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                     bigint NOT NULL REFERENCES deals(id),
  schedule_type_id            bigint NOT NULL REFERENCES reference_values(id),
  base_rate                   numeric(9,4),
  margin_rate                 numeric(9,4),
  floor_rate                  numeric(9,4),
  ceiling_rate                numeric(9,4),
  effective_date              date NOT NULL,
  expiry_date                 date,
  source_reference            varchar(255)
);

CREATE OR REPLACE TABLE pricing_history (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id                 bigint NOT NULL REFERENCES pricing_schedules(id),
  change_type_id              bigint REFERENCES reference_values(id),
  old_value_number            numeric(22,6),
  old_value_text              text,
  new_value_number            numeric(22,6),
  new_value_text              text,
  changed_at                  timestamp without time zone DEFAULT now(),
  changed_by_entity_id        bigint REFERENCES entities(id)
);

CREATE OR REPLACE TABLE drawdowns (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id                 bigint NOT NULL REFERENCES deals(id),
  requested_amount        numeric(22,2) NOT NULL,
  approved_amount         numeric(22,2),
  currency_code           varchar(3) NOT NULL,
  status_value_id         bigint REFERENCES reference_values(id),
  requested_at            timestamp without time zone DEFAULT now(),
  approved_at             timestamp without time zone
);

CREATE OR REPLACE TABLE drawdown_events (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drawdown_id             bigint NOT NULL REFERENCES drawdowns(id),
  event_type_id           bigint NOT NULL REFERENCES reference_values(id),
  status_value_id         bigint REFERENCES reference_values(id),
  occurred_at             timestamp without time zone NOT NULL,
  recorded_by_entity_id   bigint REFERENCES entities(id),
  event_notes             text,
  reference_number        varchar(255)
);

CREATE OR REPLACE TABLE drawdown_checks (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drawdown_id             bigint NOT NULL REFERENCES drawdowns(id),
  check_type_id           bigint NOT NULL REFERENCES reference_values(id),
  is_passed               boolean,
  checked_at              timestamp without time zone,
  checked_by_entity_id    bigint REFERENCES entities(id),
  notes                   text
);

CREATE OR REPLACE TABLE quotes (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  originating_entity_id       bigint REFERENCES entities(id),
  deal_id                     bigint REFERENCES deals(id),
  quote_status_id             bigint REFERENCES reference_values(id),
  valid_from                  date NOT NULL,
  valid_to                    date,
  total_amount                numeric(22,2),
  currency_code               varchar(3) NOT NULL,
  created_at                  timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE quote_recipients (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id                    bigint NOT NULL REFERENCES quotes(id),
  recipient_type              varchar(128),
  recipient_id                bigint,
  recipient_contact           varchar(255),
  channel_type_id             bigint REFERENCES reference_values(id),
  sent_at                     timestamp without time zone,
  acknowledgement_status_id   bigint REFERENCES reference_values(id)
);

CREATE OR REPLACE INDEX quote_recipients_recipient_idx ON quote_recipients (recipient_type, recipient_id);

CREATE OR REPLACE TABLE sales_orders (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id                    bigint REFERENCES quotes(id),
  deal_id                     bigint REFERENCES deals(id),
  order_status_id             bigint REFERENCES reference_values(id),
  placed_at                   timestamp without time zone DEFAULT now(),
  fulfilled_at                timestamp without time zone
);

CREATE OR REPLACE TABLE forms (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_code               varchar(128) NOT NULL,
  name                    varchar(255) NOT NULL,
  version                 integer NOT NULL,
  status_value_id         bigint REFERENCES reference_values(id),
  introduction            text,
  confirmation_statement  text,
  created_by_entity_id    bigint REFERENCES entities(id),
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  UNIQUE(form_code, version)
);

CREATE OR REPLACE TABLE form_responses (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id                 bigint NOT NULL REFERENCES forms(id),
  respondent_entity_id    bigint REFERENCES entities(id),
  subject_type            varchar(128),
  subject_id              bigint,
  status_value_id         bigint REFERENCES reference_values(id),
  submitted_at            timestamp without time zone,
  overall_comment         text
);

CREATE OR REPLACE INDEX form_responses_subject_idx ON form_responses (subject_type, subject_id);

CREATE OR REPLACE TABLE form_documents (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_response_id        bigint NOT NULL REFERENCES form_responses(id),
  document_id             bigint NOT NULL REFERENCES documents(id),
  UNIQUE(form_response_id, document_id)
);

CREATE OR REPLACE TABLE form_sections (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id                 bigint NOT NULL REFERENCES forms(id),
  section_number          integer NOT NULL,
  title                   varchar(255),
  description             text,
  UNIQUE(form_id, section_number)
);

CREATE OR REPLACE TABLE form_questions (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id              bigint REFERENCES form_sections(id),
  form_id                 bigint NOT NULL REFERENCES forms(id),
  question_number         integer NOT NULL,
  prompt                  text NOT NULL,
  response_type_id        bigint NOT NULL REFERENCES reference_values(id),
  is_required             boolean DEFAULT false,
  help_text               text,
  default_text            text,
  default_number          numeric(22,6),
  default_date            date,
  default_boolean         boolean,
  UNIQUE(form_id, question_number)
);

CREATE OR REPLACE TABLE form_question_options (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id             bigint NOT NULL REFERENCES form_questions(id),
  option_code             varchar(64) NOT NULL,
  option_label            varchar(255) NOT NULL,
  display_order           integer DEFAULT 0,
  is_active               boolean DEFAULT true,
  UNIQUE(question_id, option_code)
);

CREATE OR REPLACE TABLE form_response_answers (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  response_id             bigint NOT NULL REFERENCES form_responses(id),
  question_id             bigint NOT NULL REFERENCES form_questions(id),
  answer_text             text,
  answer_number           numeric(22,6),
  answer_date             date,
  answer_boolean          boolean,
  selected_option_code    varchar(64),
  answered_at             timestamp without time zone DEFAULT now(),
  UNIQUE(response_id, question_id)
);

CREATE OR REPLACE TABLE valuations (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  valuable_type           varchar(128) NOT NULL,
  valuable_id             bigint NOT NULL,
  valuation_type_id       bigint REFERENCES reference_values(id),
  valuation_amount        numeric(22,2) NOT NULL,
  valuation_date          date NOT NULL,
  source_reference        varchar(255),
  created_at              timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE INDEX valuations_valuable_idx ON valuations (valuable_type, valuable_id);

CREATE OR REPLACE TABLE system_jobs (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_key                 varchar(255) NOT NULL,
  arguments_text          text,
  related_record_type     varchar(128),
  related_record_id       bigint,
  status_value_id         bigint REFERENCES reference_values(id),
  available_at            timestamp without time zone,
  attempts                integer DEFAULT 0,
  last_error              text,
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now()
);

CREATE OR REPLACE TABLE audit_events (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_entity_id         bigint REFERENCES entities(id),
  scope_type              varchar(64) NOT NULL,
  scope_id                bigint,
  event_type_id           bigint REFERENCES reference_values(id),
  event_at                timestamp without time zone DEFAULT now(),
  ip_address              varchar(64),
  user_agent              varchar(255)
);

CREATE OR REPLACE TABLE audit_event_changes (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_event_id          bigint NOT NULL REFERENCES audit_events(id),
  changed_table           varchar(128) NOT NULL,
  changed_column          varchar(128) NOT NULL,
  old_value_text          text,
  old_value_number        numeric(22,6),
  old_value_boolean       boolean,
  new_value_text          text,
  new_value_number        numeric(22,6),
  new_value_boolean       boolean
);

CREATE OR REPLACE TABLE integration_settings (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_type_id     bigint NOT NULL REFERENCES reference_values(id),
  endpoint_url            varchar(512),
  account_identifier      varchar(255),
  api_key_reference       varchar(255),
  secret_reference        varchar(255),
  is_active               boolean DEFAULT true,
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  UNIQUE(integration_type_id)
);

CREATE OR REPLACE TABLE system_settings (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key             varchar(255) NOT NULL,
  scope_type              varchar(64),
  scope_id                bigint,
  value_text              text,
  value_number            numeric(22,6),
  value_boolean           boolean,
  value_date              date,
  created_at              timestamp without time zone DEFAULT now(),
  updated_at              timestamp without time zone DEFAULT now(),
  UNIQUE(setting_key, COALESCE(scope_type, ''), COALESCE(scope_id, 0))
);
